### ISSUE TITLE
FIX ComponentOperation: Operation with non-variables

### ISSUE THREAD

**Issue by Sossics** [AlamRoman/coffee-builder#1]
_num1_ is an Integer.

When you try to run one of the following codes:

1. `ComponentOperation operation = new ComponentOperation(end, null, MEMORY);`
`operation.set("num1", "$num2", "$num3", TipoOperazioni.PIU);`
2. `ComponentOperation operation = new ComponentOperation(end, null, MEMORY);`
`operation.set("num1", "1", "1", TipoOperazioni.PIU);`

1 - The test will throw the following (unhandled) exception:
`Exception in thread "main" java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')`
`at model.Components.ComponentOperation.execute(ComponentOperation.java:117)`
`at model.AlgorithmExecuter.start(AlgorithmExecuter.java:21)`
`at main.TEST.Main_TESTS.main(Main_TESTS.java:54)
`

2 - The test will throw the following exception:
`The value cannot be converted`

**Comment by Sossics** [comment]
Ez per favaro che la clutcha
